import { Marcellus, Montserrat } from "next/font/google";
import "./globals.css";

//components
import Header from "@/components/Header";
import CursorProvider from "@/components/CursorContext";
import Transition from "@/components/Transition";
import PageTransition from "@/components/PageTransition";

const marcellus = Marcellus({ 
  subsets: ["latin"],
   weight: ["400"], 
   variable: "--font-marcellus", // a unique name for the variable:
});

const montserrat = Montserrat({ 
  subsets: ["latin"],
   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], 
   variable: "--font-montserrat", // a unique name for the variable:
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-screen">
      <head>
        <link
          href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
          rel="stylesheet"
        />
        <link
          href="https://unpkg.com/swiper@8/swiper-bundle.min.css"
          rel="stylesheet"
        />
      </head>
      <body className={`${marcellus.variable} ${montserrat.
        variable} overflow-x-hidden`}
        >
          <CursorProvider>
            <Transition />
            <Header />
            <PageTransition>{children}</PageTransition>
            </CursorProvider>
          </body>
    </html>
  );
}
